M48
; DRILL file {KiCad 8.0.4} date 2024-09-28T14:18:18+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-28T14:18:18+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X97.536Y-58.45
X97.538Y-107.95
X159.258Y-58.45
X159.258Y-107.95
M30
